branch-defaults:
  deploy:
    environment: HuyService
    group_suffix: null
environment-defaults:
  HuyService-env:
    branch: null
    repository: null
global:
  application_name: huy-service
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
